import { VehicleContextProvider } from '@/state/errorState/vehicleContext';
import './globals.css';

// components
import Nav from '@/components/Nav/Nav';

// meta
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<VehicleContextProvider>
					<Nav />
					{children}
				</VehicleContextProvider>
			</body>
		</html>
	);
}
